boundaries:
  - name: RIE
    color: "#F0F0F0"
    isTrusted: False
    isFilled: True
    sub_zones:
      - name: External_Network_RIE
        color: lightgray
        isTrusted: False
        isFilled: False
  - name: infra_boundary
    isFilled: False
    line_style: dashed
    isTrusted: True
    sub_zones:
      - name: app_zone
        color: red
        isTrusted: True
        isFilled: False
      - name: app_zone_fallback
        color: blue
        isTrusted: True
        isFilled: False

actors:
  - name: Operator
    boundary: infra_boundary
  - name: Admin
    boundary: infra_boundary

servers:
  - name: Router_RIE_InfraBoundary
    stereotype: Server
  - name: Switch_Main_Fallback
    boundary: infra_boundary
    stereotype: Server
  - name: Switch_Main
    boundary: app_zone
    stereotype: Server
  - name: Server_1
    boundary: app_zone
    stereotype: Server
  - name: Frontend_1
    boundary: app_zone
    stereotype: Server
  - name: Server_2
    boundary: app_zone
    stereotype: Server
  - name: Frontend_2
    boundary: app_zone
    stereotype: Server
  - name: Server_3
    boundary: app_zone
    stereotype: Server
  - name: Frontend_3
    boundary: app_zone
    stereotype: Server
  - name: Server_4
    boundary: app_zone
    stereotype: Server
  - name: Frontend_4
    boundary: app_zone
    stereotype: Server
  - name: Server_5
    boundary: app_zone
    stereotype: Server
  - name: Frontend_5
    boundary: app_zone
    stereotype: Server
  - name: Switch_Fallback
    boundary: app_zone_fallback
    stereotype: Server
  - name: Server_1_fallback
    boundary: app_zone_fallback
    stereotype: Server
  - name: Frontend_1_fallback
    boundary: app_zone_fallback
    stereotype: Server
  - name: Server_2_fallback
    boundary: app_zone_fallback
    stereotype: Server
  - name: Frontend_2_fallback
    boundary: app_zone_fallback
    stereotype: Server
  - name: Server_3_fallback
    boundary: app_zone_fallback
    stereotype: Server
  - name: Frontend_3_fallback
    boundary: app_zone_fallback
    stereotype: Server
  - name: Server_4_fallback
    boundary: app_zone_fallback
    stereotype: Server
  - name: Frontend_4_fallback
    boundary: app_zone_fallback
    stereotype: Server
  - name: Server_5_fallback
    boundary: app_zone_fallback
    stereotype: Server
  - name: Frontend_5_fallback
    boundary: app_zone_fallback
    stereotype: Server
  - name: External_Network_RIE
    boundary: RIE
    stereotype: Server

data:
  - name: Any Traffic
    description: "Any type of network traffic"
    classification: "PUBLIC"
  - name: Web Traffic
    description: "Standard web requests/responses"
    classification: "PUBLIC"
  - name: SSH Traffic
    description: "Secure Shell remote access"
    classification: "TOP_SECRET"
    credentialsLife: "SHORT"
  - name: I/O Traffic
    description: "Input/Output communication"
    classification: "INTERNAL"

dataflows:
  - name: RIE_to_Router
    from: External_Network_RIE
    to: Router_RIE_InfraBoundary
    protocol: Any
    data: Any Traffic
    description: "Traffic from RIE to Router"
  - name: Router_to_InfraBoundary_Internal
    from: Router_RIE_InfraBoundary
    to: Switch_Main_Fallback
    protocol: Any
    data: Any Traffic
    description: "Traffic from Router to infra_boundary internal network"
  - name: Operator_to_Frontend_1
    from: Operator
    to: Frontend_1
    protocol: HTTPS
    data: Web Traffic
    description: "Operator connects to Frontend_1"
  - name: Operator_to_Frontend_2
    from: Operator
    to: Frontend_2
    protocol: HTTPS
    data: Web Traffic
    description: "Operator connects to Frontend_2"
  - name: Operator_to_Frontend_3
    from: Operator
    to: Frontend_3
    protocol: HTTPS
    data: Web Traffic
    description: "Operator connects to Frontend_3"
  - name: Operator_to_Frontend_4
    from: Operator
    to: Frontend_4
    protocol: HTTPS
    data: Web Traffic
    description: "Operator connects to Frontend_4"
  - name: Operator_to_Frontend_5
    from: Operator
    to: Frontend_5
    protocol: HTTPS
    data: Web Traffic
    description: "Operator connects to Frontend_5"
  - name: Admin_to_Switch_Main
    from: Admin
    to: Switch_Main
    protocol: SSH
    data: SSH Traffic
    description: "Admin connects to Switch_Main"
  - name: Switch_Main_Fallback_to_Switch_Main
    from: Switch_Main_Fallback
    to: Switch_Main
    protocol: Any
    data: Any Traffic
    description: "Switch_Main_Fallback connects to Switch_Main"
  - name: Server_1_to_Switch_Main
    from: Server_1
    to: Switch_Main
    protocol: Any
    data: Any Traffic
  - name: Frontend_1_to_Switch_Main
    from: Frontend_1
    to: Switch_Main
    protocol: Any
    data: Any Traffic
  - name: Server_2_to_Switch_Main
    from: Server_2
    to: Switch_Main
    protocol: Any
    data: Any Traffic
  - name: Frontend_2_to_Switch_Main
    from: Frontend_2
    to: Switch_Main
    protocol: Any
    data: Any Traffic
  - name: Server_3_to_Switch_Main
    from: Server_3
    to: Switch_Main
    protocol: Any
    data: Any Traffic
  - name: Frontend_3_to_Switch_Main
    from: Frontend_3
    to: Switch_Main
    protocol: Any
    data: Any Traffic
  - name: Server_4_to_Switch_Main
    from: Server_4
    to: Switch_Main
    protocol: Any
    data: Any Traffic
  - name: Frontend_4_to_Switch_Main
    from: Frontend_4
    to: Switch_Main
    protocol: Any
    data: Any Traffic
  - name: Server_5_to_Switch_Main
    from: Server_5
    to: Switch_Main
    protocol: Any
    data: Any Traffic
  - name: Frontend_5_to_Switch_Main
    from: Frontend_5
    to: Switch_Main
    protocol: Any
    data: Any Traffic
  - name: Operator_to_Frontend_1_fallback
    from: Operator
    to: Frontend_1_fallback
    protocol: HTTPS
    data: Web Traffic
    description: "Operator connects to Frontend_1_fallback"
  - name: Operator_to_Frontend_2_fallback
    from: Operator
    to: Frontend_2_fallback
    protocol: HTTPS
    data: Web Traffic
    description: "Operator connects to Frontend_2_fallback"
  - name: Operator_to_Frontend_3_fallback
    from: Operator
    to: Frontend_3_fallback
    protocol: HTTPS
    data: Web Traffic
    description: "Operator connects to Frontend_3_fallback"
  - name: Operator_to_Frontend_4_fallback
    from: Operator
    to: Frontend_4_fallback
    protocol: HTTPS
    data: Web Traffic
    description: "Operator connects to Frontend_4_fallback"
  - name: Operator_to_Frontend_5_fallback
    from: Operator
    to: Frontend_5_fallback
    protocol: HTTPS
    data: Web Traffic
    description: "Operator connects to Frontend_5_fallback"
  - name: Admin_to_Switch_Fallback
    from: Admin
    to: Switch_Fallback
    protocol: SSH
    data: SSH Traffic
    description: "Admin connects to Switch_Fallback"
  - name: Switch_Main_Fallback_to_Switch_Fallback
    from: Switch_Main_Fallback
    to: Switch_Fallback
    protocol: Any
    data: Any Traffic
    description: "Switch_Main_Fallback connects to Switch_Fallback"
  - name: Server_1_fallback_to_Switch_Fallback
    from: Server_1_fallback
    to: Switch_Fallback
    protocol: Any
    data: Any Traffic
  - name: Frontend_1_fallback_to_Switch_Fallback
    from: Frontend_1_fallback
    to: Switch_Fallback
    protocol: Any
    data: Any Traffic
  - name: Server_2_fallback_to_Switch_Fallback
    from: Server_2_fallback
    to: Switch_Fallback
    protocol: Any
    data: Any Traffic
  - name: Frontend_2_fallback_to_Switch_Fallback
    from: Frontend_2_fallback
    to: Switch_Fallback
    protocol: Any
    data: Any Traffic
  - name: Server_3_fallback_to_Switch_Fallback
    from: Server_3_fallback
    to: Switch_Fallback
    protocol: Any
    data: Any Traffic
  - name: Frontend_3_fallback_to_Switch_Fallback
    from: Frontend_3_fallback
    to: Switch_Fallback
    protocol: Any
    data: Any Traffic
  - name: Server_4_fallback_to_Switch_Fallback
    from: Server_4_fallback
    to: Switch_Fallback
    protocol: Any
    data: Any Traffic
  - name: Frontend_4_fallback_to_Switch_Fallback
    from: Frontend_4_fallback
    to: Switch_Fallback
    protocol: Any
    data: Any Traffic
  - name: Server_5_fallback_to_Switch_Fallback
    from: Server_5_fallback
    to: Switch_Fallback
    protocol: Any
    data: Any Traffic
  - name: Frontend_5_fallback_to_Switch_Fallback
    from: Frontend_5_fallback
    to: Switch_Fallback
    protocol: Any
    data: Any Traffic

protocol_styles:
  - name: HTTPS
    color: darkgreen
    line_style: solid
  - name: SSH
    color: blue
    line_style: dashed
  - name: I/O
    color: orange
    line_style: dotted
