name: Code Coverage Check

on:
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage pytest

    - name: Run tests and generate coverage report
      run: |
        coverage run --source=threat_analysis -m pytest

    - name: Check coverage percentage
      run: |
        coverage report --fail-under=70
