name: Sync Docs to Wiki

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'docs/**.md'

jobs:
  sync-to-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Checkout wiki repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Sync markdown files from docs
        run: |
          # Create wiki directory if it doesn't exist
          mkdir -p wiki
          
          # Process all .md files in docs
          find docs -name "*.md" -type f | while read file; do
            # Get just the filename without path
            filename=$(basename "$file")
            # Remove .md extension for wiki page name
            wikiname="${filename%.md}"
            
            cp "$file" "wiki/${wikiname}.md"
            echo "Synced: $file -> wiki/${wikiname}.md"
          done
          
      - name: Commit and push changes to wiki
        run: |
          cd wiki
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-sync documentation from docs/"
            git push
          fi